name: Playwright Java CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install dependencies
      run: mvn clean install -DskipTests

    - name: Install Playwright Browsers
      run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"

    - name: Run tests
      run: mvn test

    - name: Install Allure
      run: |
        sudo apt-add-repository ppa:qameta/allure
        sudo apt-get update
        sudo apt-get install allure -y

    - name: Generate Allure Report
      run: allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report